### PR TITLE
📝 README: Added new library

### PR DESCRIPTION
**Pull request by motss**
`normalize-diacritics` has been added to the `library` section.

### CODE REVIEW

**Comment by motss** [comment]
@olivewind This fixes #7.

**Review by olivewind — CHANGES_REQUESTED** [review]
image

duplicate

**Comment by olivewind** [comment]
@motss  maybe you can create a pr at https://github.com/denolib/awesome-deno

**Comment by motss** [comment]
@olivewind Done. PTAL https://github.com/denolib/awesome-deno/pull/16

**Comment by motss** [comment]
Closed at https://github.com/denolib/awesome-deno/pull/16

**Pull request closed without merging**
